# Generated by Django 4.2.3 on 2023-07-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf',
        ),
    ]
