# Generated by Django 4.2.3 on 2023-07-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_book_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
