# Generated by Django 4.2.3 on 2023-07-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.URLField(default='https://alexmonaco.net/wp-content/uploads/2022/02/Atomic-Habits-265x400.jpg.webp'),
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.JSONField(default=list),
        ),
    ]
