# Generated by Django 4.2.3 on 2023-07-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_book_cover_book_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.URLField(default='https://alexmonaco.net/wp-content/uploads/2022/02/Atomic-Habits-265x400.jpg'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
