# Generated by Django 4.2.3 on 2023-07-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_book_cover_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(upload_to=''),
        ),
    ]
